CREATE TABLE AK171762.DIVISION
(
    type nchar(50) NOT NULL,
    rank nchar(3) NOT NULL,
);
GO

ALTER TABLE AK171762.DIVISION
    ADD CONSTRAINT PK_TYPE_RANK
        PRIMARY KEY (type);

-- DROP TABLE AK171762.DIVISION;