CREATE TABLE AK171762.RECRUITER
(
    Name VARCHAR(50) NOT NULL,
    Affiliate VARCHAR(100) NOT NULL,
    Rank VARCHAR(20) NULL,
);
GO

ALTER TABLE AK171762.RECRUITER
    ADD CONSTRAINT PK_NAME_AFFILIATE_RANK
        PRIMARY KEY (Name);

-- DROP TABLE AK171762.RECRUITER;