CREATE TABLE AK171762.SPONSOR
(
    Name VARCHAR(50) NOT NULL,
    Donation int NULL,
);
GO

ALTER TABLE AK171762.SPONSOR
    ADD CONSTRAINT PK_NAME
        PRIMARY KEY (Name);

-- DROP TABLE AK171762.SPONSOR;